- name: install package
  hosts: all
  become: true
  tasks:
    - name: dnfinstaller
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: copy file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
