- name: Install node_exporter based on architecture
  hosts: local
  vars_files:
    - vault.yaml
  gather_facts: yes
  become: yes
  vars:
    node_exporter_version: "1.9.1"
  tasks:
    - name: Verify node_exporter installation
      command: /usr/local/bin/node_exporter --version
      register: version_check
      ignore_errors: yes
      failed_when: version_check.rc != 0
    - name: Display node_exporter version
      debug:
        msg: "Node Exporter is not installed"


